### ISSUE TITLE
Assuming this is what is meant by not supporting custom bindings?

### ISSUE THREAD

**Issue by jwolfm98** [andrewdsmith/edxlc#1]
![Capture](https://user-images.githubusercontent.com/12657165/137563248-3d8cacc0-b81c-4ba3-80cf-8c297a840566.PNG)

Where the actual location is
_C:\Users\\%USER%\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.3.0.binds_

Is there not a cli argument to force it to look at a specific binds file? I'm guessing this currently uses the file at
_.\Elite Dangerous\Products\elite-dangerous-64\ControlSchemes\SaitekX52Pro.binds_

**Comment by andrewdsmith** [comment]
Thanks for reporting this! Currently it's hard-coded to `Custom.4.0.binds`, i.e. for Odyssey. Am I right in assuming you're using Horizons?

I was being lazy and waiting until this was needed by someone before making this an option. Looks like that time has arrived! I'll add an option to the config file to allow this to be set. I should be done in a day or two.
